# Generated by Django 5.0.6 on 2024-07-05 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_organisation_orgid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AddField(
            model_name='organisation',
            name='orgId',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
