# Generated by Django 5.0.6 on 2024-07-06 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_organisation_id_organisation_orgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
