# Generated by Django 5.0.6 on 2024-07-06 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organisation_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userId',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
